#!/usr/bin/env node
/**
 * Generate the Champions League LEAGUE-PHASE data files (36 teams · 8 matchdays) from football-data.org,
 * mirroring the domestic schedule/results format so the existing tower renders it unchanged.
 *
 *   FOOTBALL_DATA_API_KEY=… node scripts/gen-ucl.mjs --season 2025-26   (fd season year = 2025)
 *
 * Writes src/data/schedule-CL-<season>.js (TEAMS + MATCHDAYS=8) and results-CL-<season>.js (RESULTS).
 * Also prints the crest URL per team code (fed to scripts/fetch-ucl-crests for CL_<code>.png).
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dir = path.dirname(fileURLToPath(import.meta.url))
const DATA = path.join(__dir, '..', 'src', 'data')
const opt = (f, d) => { const i = process.argv.indexOf(f); return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : d }
const SEASON = opt('--season', '2025-26')
const FD_YEAR = parseInt(SEASON.slice(0, 4), 10)
const KEY = process.env.FOOTBALL_DATA_API_KEY
if (!KEY) { console.error('Set FOOTBALL_DATA_API_KEY'); process.exit(1) }

// brand primary colour per team code (tla). Text ink is derived by contrast() in the app.
const COLORS = {
  AEP: '#00539F', AJA: '#D2122E', ARS: '#EF0107', ASM: '#CE2029', ATA: '#2A5AA8', ATH: '#EE2523',
  ATL: '#CB3524', B04: '#E32219', BEN: '#E00000', BRU: '#005CA9', BVB: '#FDE100', CHE: '#034694',
  FCB: '#DC052D', FK: '#F9D616', GAL: '#CD2932', INT: '#1B2A6B', JUV: '#111111', KAI: '#F2C200',
  KOB: '#002B5C', LIV: '#C8102E', MAR: '#2FAEE0', MCI: '#6CABDD', NAP: '#12A0D7', NEW: '#241F20',
  OLY: '#DF1E26', PSG: '#0A1A44', PSV: '#ED1C24', QAR: '#0A5DA8', RMA: '#103A8F', SGE: '#E1000F',
  SLP: '#D31217', SPO: '#007A3D', TOT: '#132257', USG: '#0A3D7C', VIL: '#FDE100',
}
COLORS.BAR = '#A50044'
// short display names (kept tidy for the modal header)
const SHORT = { AEP: 'Paphos', AJA: 'Ajax', ATL: 'Atlético Madrid', ATH: 'Athletic Club', BAR: 'Barcelona', B04: 'Leverkusen', BEN: 'Benfica', BRU: 'Club Brugge', BVB: 'Dortmund', FCB: 'Bayern München', FK: 'Bodø/Glimt', GAL: 'Galatasaray', INT: 'Inter', KAI: 'Kairat', KOB: 'København', MAR: 'Marseille', NAP: 'Napoli', OLY: 'Olympiacos', PSG: 'Paris Saint-Germain', QAR: 'Qarabağ', RMA: 'Real Madrid', SGE: 'Eintracht Frankfurt', SLP: 'Slavia Praha', SPO: 'Sporting CP', USG: 'Union SG' }

const r = await fetch(`https://api.football-data.org/v4/competitions/CL/matches?season=${FD_YEAR}`, { headers: { 'X-Auth-Token': KEY } })
if (!r.ok) { console.error('HTTP', r.status); process.exit(1) }
const data = await r.json()
const lp = (data.matches || []).filter(m => m.stage === 'LEAGUE_STAGE')

// pass 1: unique team id -> team object; assign a unique short code (tla, or a shortName-derived
// alternate when a tla is reused for two different clubs).
const byId = {}
for (const m of lp) for (const t of [m.homeTeam, m.awayTeam]) if (!byId[t.id]) byId[t.id] = t
const codeOf = {}, used = {}
for (const id of Object.keys(byId)) {
  const t = byId[id]
  let c = t.tla
  if (used[c]) { const base = (t.shortName || t.name).toUpperCase().replace(/[^A-Z]/g, '').slice(0, 3) || c; c = base; let n = 1; while (used[c]) c = base.slice(0, 2) + (n++) }
  used[c] = 1; codeOf[id] = c
}

const TEAMS = {}, RESULTS = {}, crests = {}
const ensure = (t) => {
  const c = codeOf[t.id]
  if (!TEAMS[c]) { TEAMS[c] = { name: SHORT[c] || t.shortName || t.name, abbr: c, primary: COLORS[c] || '#8A8F98', games: [] }; crests[c] = t.crest }
  return c
}
for (const m of lp) {
  const h = ensure(m.homeTeam), a = ensure(m.awayTeam)
  const id = String(m.id), w = m.matchday
  const venue = m.venue || ''
  TEAMS[h].games.push({ id, w, opp: a, oppFull: TEAMS[a].name, ha: 'H', venue })
  TEAMS[a].games.push({ id, w, opp: h, oppFull: TEAMS[h].name, ha: 'A', venue })
  if (m.status === 'FINISHED' && m.score?.fullTime?.home != null) RESULTS[id] = { hg: m.score.fullTime.home, ag: m.score.fullTime.away }
}

fs.writeFileSync(path.join(DATA, `schedule-CL-${SEASON}.js`), `// UEFA Champions League league phase — 36 teams · 8 matchdays. Generated by scripts/gen-ucl.mjs.\nexport const MATCHDAYS = 8\nexport const TEAMS = ${JSON.stringify(TEAMS)}\n`)
fs.writeFileSync(path.join(DATA, `results-CL-${SEASON}.js`), `// Real results, keyed by unique matchId -> {hg,ag}. Generated by scripts/gen-ucl.mjs (football-data.org).\nexport const RESULTS = ${JSON.stringify(RESULTS)}\n`)
fs.writeFileSync(path.join(__dir, 'ucl-crests.json'), JSON.stringify(crests, null, 0))

const games = Object.values(TEAMS).map(t => t.games.length)
console.log(`CL ${SEASON}: ${Object.keys(TEAMS).length} teams, ${lp.length} matches, ${Object.keys(RESULTS).length} played`)
console.log(`games per team: min ${Math.min(...games)} max ${Math.max(...games)}`)
console.log(`crest list → scripts/ucl-crests.json`)
